float64 GNSS_time
float64 total_sv
float64 prn_satellites_index
float64 pseudorange
float64 raw_pseudorange
float64 carrier_phase
float64 lamda
float64 snr
float64 elevation
float64 azimuth
float64 err_tropo
float64 err_iono
float64 sat_clk_err
float64 sat_pos_x
float64 sat_pos_y
float64 sat_pos_z
#float64 GNSSCovariance
int64 visable #0-Not sure 1-visable 2-invisable
string  sat_system
int64 visable3DMA # ground truth visibility from 3DMA
float64 prE3dMA # ground truth pseudorange error from 3DMA

